# Generated by Django 3.2.8 on 2022-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
