# Generated by Django 4.1 on 2022-08-10 07:33

from django.db import migrations, models
import gif_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ("gif_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[gif_app.validators.check_splcharacter],
            ),
        ),
    ]
